version: '2'
services:
    web:
        build: .
        depends_on:
            - mongo
            - redis
        env_file: .env
        environment:
            - PORT=3000
            - DATABASE_URL=mongodb://mongo/db,
            - REDIS_URL=redis://redis
            - DEBUG=*,-mquery
        ports:
            - "$PORT:3000"
    mongo:
        image: mongo
    redis:
        image: redis
